name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-22.04
    steps:
      - uses: kawamataryo/lapras-card-readme@v1.2.1
        with:
          SHARE_ID: developermasaki
